################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/HardwareSerial.cpp \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/IPAddress.cpp \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/Print.cpp \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/RingBuffer.cpp \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/Stream.cpp \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/Tone.cpp \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/WInterrupts.cpp \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/WMath.cpp \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/WString.cpp \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/abi.cpp \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/main.cpp \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/new.cpp \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/wiring_pulse.cpp 

C_SRCS += \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/board.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/hooks.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/itoa.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/pins_arduino.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/syscalls_stm32.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/wiring_analog.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/wiring_digital.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/wiring_shift.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/wiring_time.c 

C_DEPS += \
./core/core/board.c.d \
./core/core/hooks.c.d \
./core/core/itoa.c.d \
./core/core/pins_arduino.c.d \
./core/core/syscalls_stm32.c.d \
./core/core/wiring_analog.c.d \
./core/core/wiring_digital.c.d \
./core/core/wiring_shift.c.d \
./core/core/wiring_time.c.d 

AR_OBJ += \
./core/core/HardwareSerial.cpp.o \
./core/core/IPAddress.cpp.o \
./core/core/Print.cpp.o \
./core/core/RingBuffer.cpp.o \
./core/core/Stream.cpp.o \
./core/core/Tone.cpp.o \
./core/core/WInterrupts.cpp.o \
./core/core/WMath.cpp.o \
./core/core/WString.cpp.o \
./core/core/abi.cpp.o \
./core/core/board.c.o \
./core/core/hooks.c.o \
./core/core/itoa.c.o \
./core/core/main.cpp.o \
./core/core/new.cpp.o \
./core/core/pins_arduino.c.o \
./core/core/syscalls_stm32.c.o \
./core/core/wiring_analog.c.o \
./core/core/wiring_digital.c.o \
./core/core/wiring_pulse.cpp.o \
./core/core/wiring_shift.c.o \
./core/core/wiring_time.c.o 

CPP_DEPS += \
./core/core/HardwareSerial.cpp.d \
./core/core/IPAddress.cpp.d \
./core/core/Print.cpp.d \
./core/core/RingBuffer.cpp.d \
./core/core/Stream.cpp.d \
./core/core/Tone.cpp.d \
./core/core/WInterrupts.cpp.d \
./core/core/WMath.cpp.d \
./core/core/WString.cpp.d \
./core/core/abi.cpp.d \
./core/core/main.cpp.d \
./core/core/new.cpp.d \
./core/core/wiring_pulse.cpp.d 


# Each subdirectory must supply rules for building sources it contributes
core/core/HardwareSerial.cpp.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/HardwareSerial.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/IPAddress.cpp.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/IPAddress.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/Print.cpp.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/Print.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/RingBuffer.cpp.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/RingBuffer.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/Stream.cpp.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/Stream.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/Tone.cpp.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/Tone.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/WInterrupts.cpp.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/WInterrupts.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/WMath.cpp.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/WMath.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/WString.cpp.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/WString.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/abi.cpp.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/abi.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/board.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/board.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/hooks.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/hooks.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/itoa.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/itoa.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/main.cpp.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/main.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/new.cpp.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/new.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/pins_arduino.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/pins_arduino.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/syscalls_stm32.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/syscalls_stm32.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/wiring_analog.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/wiring_analog.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/wiring_digital.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/wiring_digital.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/wiring_pulse.cpp.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/wiring_pulse.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/wiring_shift.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/wiring_shift.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/wiring_time.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/wiring_time.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '


