################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/interrupt.cpp 

S_UPPER_SRCS += \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/startup_stm32yyxx.S 

C_SRCS += \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/PinConfigured.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/PortNames.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/analog.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/clock.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/core_callback.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/digital_io.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/hal_uart_emul.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/hw_config.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/low_power.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/pinmap.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/rtc.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/spi_com.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/stm32_def.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/stm32_eeprom.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/system_stm32yyxx.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/timer.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/twi.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/uart.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/uart_emul.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/usb_device_core.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/usb_device_ctlreq.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/usb_device_ioreq.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/usb_interface.c \
/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/usbd_hid_composite.c 

C_DEPS += \
./core/core/stm32/PinConfigured.c.d \
./core/core/stm32/PortNames.c.d \
./core/core/stm32/analog.c.d \
./core/core/stm32/clock.c.d \
./core/core/stm32/core_callback.c.d \
./core/core/stm32/digital_io.c.d \
./core/core/stm32/hal_uart_emul.c.d \
./core/core/stm32/hw_config.c.d \
./core/core/stm32/low_power.c.d \
./core/core/stm32/pinmap.c.d \
./core/core/stm32/rtc.c.d \
./core/core/stm32/spi_com.c.d \
./core/core/stm32/stm32_def.c.d \
./core/core/stm32/stm32_eeprom.c.d \
./core/core/stm32/system_stm32yyxx.c.d \
./core/core/stm32/timer.c.d \
./core/core/stm32/twi.c.d \
./core/core/stm32/uart.c.d \
./core/core/stm32/uart_emul.c.d \
./core/core/stm32/usb_device_core.c.d \
./core/core/stm32/usb_device_ctlreq.c.d \
./core/core/stm32/usb_device_ioreq.c.d \
./core/core/stm32/usb_interface.c.d \
./core/core/stm32/usbd_hid_composite.c.d 

AR_OBJ += \
./core/core/stm32/PinConfigured.c.o \
./core/core/stm32/PortNames.c.o \
./core/core/stm32/analog.c.o \
./core/core/stm32/clock.c.o \
./core/core/stm32/core_callback.c.o \
./core/core/stm32/digital_io.c.o \
./core/core/stm32/hal_uart_emul.c.o \
./core/core/stm32/hw_config.c.o \
./core/core/stm32/interrupt.cpp.o \
./core/core/stm32/low_power.c.o \
./core/core/stm32/pinmap.c.o \
./core/core/stm32/rtc.c.o \
./core/core/stm32/spi_com.c.o \
./core/core/stm32/startup_stm32yyxx.S.o \
./core/core/stm32/stm32_def.c.o \
./core/core/stm32/stm32_eeprom.c.o \
./core/core/stm32/system_stm32yyxx.c.o \
./core/core/stm32/timer.c.o \
./core/core/stm32/twi.c.o \
./core/core/stm32/uart.c.o \
./core/core/stm32/uart_emul.c.o \
./core/core/stm32/usb_device_core.c.o \
./core/core/stm32/usb_device_ctlreq.c.o \
./core/core/stm32/usb_device_ioreq.c.o \
./core/core/stm32/usb_interface.c.o \
./core/core/stm32/usbd_hid_composite.c.o 

S_UPPER_DEPS += \
./core/core/stm32/startup_stm32yyxx.S.d 

CPP_DEPS += \
./core/core/stm32/interrupt.cpp.d 


# Each subdirectory must supply rules for building sources it contributes
core/core/stm32/PinConfigured.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/PinConfigured.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/stm32/PortNames.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/PortNames.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/stm32/analog.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/analog.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/stm32/clock.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/clock.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/stm32/core_callback.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/core_callback.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/stm32/digital_io.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/digital_io.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/stm32/hal_uart_emul.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/hal_uart_emul.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/stm32/hw_config.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/hw_config.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/stm32/interrupt.cpp.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/interrupt.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/stm32/low_power.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/low_power.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/stm32/pinmap.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/pinmap.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/stm32/rtc.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/rtc.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/stm32/spi_com.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/spi_com.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/stm32/startup_stm32yyxx.S.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/startup_stm32yyxx.S
	@echo 'Building file: $<'
	@echo 'Starting S compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -x assembler-with-cpp "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)"  "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/stm32/stm32_def.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/stm32_def.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/stm32/stm32_eeprom.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/stm32_eeprom.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/stm32/system_stm32yyxx.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/system_stm32yyxx.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/stm32/timer.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/timer.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/stm32/twi.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/twi.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/stm32/uart.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/uart.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/stm32/uart_emul.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/uart_emul.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/stm32/usb_device_core.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/usb_device_core.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/stm32/usb_device_ctlreq.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/usb_device_ctlreq.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/stm32/usb_device_ioreq.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/usb_device_ioreq.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/stm32/usb_interface.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/usb_interface.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core/core/stm32/usbd_hid_composite.c.o: /home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/usbd_hid_composite.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@/home/adrian/ws/myTurtlebot_core/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD "-I" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/avr" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Inc/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/STM32L4xx_HAL_Driver/Src/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/STM32L4xx/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG/usb" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32L4xx -DARDUINO=10802 -DARDUINO_NUCLEO_L476RG -DARDUINO_ARCH_STM32 -DBOARD_NAME="NUCLEO_L476RG"  -DSTM32L476xx  -DHAL_UART_MODULE_ENABLED "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/tools/CMSIS/5.3.0/CMSIS/Core/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Include/" "-I/home/adrian/sloeber//arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/system/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/"   -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/cores/arduino" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/variants/NUCLEO_L476RG" -I"/home/adrian/sloeber/arduinoPlugin/libraries/IMU/MPU9250-master/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/msgs/common_msgs-jade-devel" -I"/home/adrian/sloeber/arduinoPlugin/libraries/PID/Arduino-PID" -I"/home/adrian/sloeber/arduinoPlugin/libraries/pololu/dual-vnh5019-motor-shield" -I"/home/adrian/sloeber/arduinoPlugin/libraries/ros_serial/rosserial-melodic" -I"/home/adrian/sloeber/arduinoPlugin/libraries/rosComm/ros_comm" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Rosserial_Arduino_Library/0.7.9/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/Time/1.5.0" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/Wire/src" -I"/home/adrian/sloeber/arduinoPlugin/libraries/gtest/1.0.1" -I"/home/adrian/sloeber/arduinoPlugin/packages/STM32/hardware/stm32/1.3.0/libraries/SPI/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '


